
CREATE NONCLUSTERED INDEX [idx_formfield_values] ON [dbo].[formField]
(
	[kioskID] ASC,
	[kioskSiteUUID] ASC,
	[formFieldType] ASC,
	[formFieldID] ASC,
	[formTypePublicKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [idx_form_values] ON [dbo].[formCreateFieldValue]
(
	[fcID] ASC,
	[version] ASC,
	[formFieldID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO