SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[gas](
	[gasID]  [int] IDENTITY(1,1) NOT NULL,
	[kioskID] [int] NULL,
        [gas] [varchar](50) NOT NULL,
	[gasName] [varchar](500) NOT NULL,
	[gasIsActive] [bit] NOT NULL
 CONSTRAINT [PK_gasID_1] PRIMARY KEY CLUSTERED 
(
	gasID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO